version: '3.3'

services:
  space.api:
    # build: ./
    image: space.api
    volumes:
     - type: bind
       source: ${SSH_AUTH_SOCK}
       target: ${SSH_AUTH_SOCK}
    container_name: space.api
    environment:
      - MQTT_HOST=mqtt_host
      - MQTT_USER=super_secret_username
      - MQTT_USER_PW=super_secret_password
      - SSH_AUTH_SOCK

    restart: unless-stopped
