version: '3.8'

services:
  space.api:
    build .
    # image: space.api
    volumes:
     - type: bind
       source: ${SSH_AUTH_SOCK}
       target: ${SSH_AUTH_SOCK}
     - $PWD:/usr/src/app

    container_name: space.api
    environment:
      - MQTT_HOST=lora.lug-saar.de
      - MQTT_USER=lugsaar
      - MQTT_USER_PW=pB62h4HQJbFx3s
      - SSH_AUTH_SOCK

    restart: unless-stopped
    user: 1001:1001
